FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install && npm cache clean --force

FROM node:18-alpine AS dev

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
