services: 
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    env_file:
      - .env.development
      
  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile.dev
    container_name: product-service
    ports:
      - '4001:3000'
    env_file:
      - .env.development
    depends_on:
      - mongodb
    restart: unless-stopped  
    networks:
      - backend
    volumes:
      - ./services/product-service:/app
      - /app/node_modules


  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
