services: 
  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - backend 
    volumes:
      - ./services/auth-service:/app
      - /app/node_modules

  product-service:
    build:
      context: ./services/product-service
      dockerfile: Dockerfile.dev
    container_name: product-service
    ports:
      - '4001:3000'
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped  
    networks:
      - backend
    volumes:
      - ./services/product-service:/app
      - /app/node_modules

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    depends_on:
      - mongodb
    ports:
      - "3002:3002"
    env_file:
      - .env
    networks:
      - backend
    volumes:
      - ./services/order-service:/app
      - /app/node_modules

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
